export const GET_ALL_CHARACTERS = 'GET_ALL_CHARACTERS';
export const GET_SPECIFIC_CHARACTERS = 'GET_SPECIFIC_CHARACTERS';
export const GET_ALL_COMICS = 'GET_ALL_COMICS';
export const SET_PAGE_NUMBER = 'SET_PAGE_NUMBER';
export const FETCHING_ANOTHER_PAGE = 'FETCHING_ANOTHER_PAGE';
export const ANOTHER_PAGE_FETCHED = 'ANOTHER_PAGE_FETCHED';
export const SHOWING_HERO_DETAILS = 'SHOWING_HERO_DETAILS';
export const GOTO_HOME_PAGE = 'GOTO_HOME_PAGE';



export const GET_HERO_DETAILS = 'FETCHING_HERO_DETAILS';
export const GET_HERO_DETAILS_SUCCESS = 'FETCHING_HERO_DETAILS_SUCCESS';